services:
  postgres-db:
    container_name: postgres-database-test
    image: postgres:16-alpine
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456
  pgAdminServer:
    depends_on:
      - postgres-db
    container_name: pgadmin-server-test
    image: dpage/pgadmin4:6.17
    environment:
      - PGADMIN_DEFAULT_PASSWORD=123456
      - PGADMIN_DEFAULT_EMAIL=superman@google.com
    ports:
      - 8080:80

volumes:
  postgres-db:
    #Esto permite tomar el volumen ya creado si es que existe
    # external: true